import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./component/navbar/Navbar";
import Footer from "./component/footer/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ margin: 0, padding: 0,backgroundColor:"rgb(0, 22, 28)" }}
      >
      
      <div className="mainvideo">
      <video
          autoPlay
          loop
          muted
          playsInline
          style={{
            position: "absolute", 
            top: 0,
            left: 0,
            width:"1600px",
            height: "700px",
            margin: "auto", 
            objectFit: "cover", 
            zIndex: "-1", 
            right: 0, 
           
          
           
          }}
        >
          <source src="/MatrixVideo.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
      </div>
       
        
        <div
          style={{
            position: "relative", 
            zIndex: 1,
            maxWidth: "1440px",
           
            margin: "auto", 
            color: "white", 
          }}
        >
        
          <Navbar />
        
      
          <div style={{ padding: "20px", marginTop:"100px" }}>{children}</div>
        </div>
        <Footer/>
        
      </body>
    </html>
  );
}
